site_name: VecDB Documentation
nav:
  - Home: index.md
  - Usage: usage.md
  - Modules: modules.md
theme:
  name: material
  palette:
    primary: indigo
  features:
    - content.code.copy
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
